name: binary_expression_tree
description: A simple binary expression tree.
version: 1.0.8
homepage: https://github.com/IvoSchols/dart-binary-expression-tree

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
